sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: B6L1simRF45kM6QFpXp3zAwl9oVhaS/0mv0zKJpXlCh4xGRRE9GuiPelrY3O5oXP8DaGdJZzZp4KApugAjHA1bvk0NmaA9cQjV4gZg87rMzHlloUwnQGN8Aiv7BnrPz8P5PU266nuGCTAhy1ID1hOs+7wD6Hj1mK2YnqyMjUPCHgM5K9A+5o4HpI//DpnCiz6KnyuGef3/xZ7tr4f3rR05MXrhv5lQz8csR+kA+Hx/3VPKbK6/qStjnChSWdQ+heDHUQ9f9ZgXiLmqFDhNO5pGjYy4qo381f8ArTKYIP9wWhay6xPZgYS5qkbPXoA1DucXvxm85fRRfsa0rsI1kCePSTgfZ3Phex9m0mtJ0Y2EGzfWimq/i+nZkdeLV6l7hcQpMEMOoicm8N74f6WmT6c1tiV2wJE3AZA0eK2L6itLY/43ORSfl42/N87jQD+qJBL6ytHquAS+YNyWPCxPMfksri3ETD/n+ElQjspBh+tPi9Xfn2jiyeQIZlAB892V2PTgcUdTLQCO7NIdxQlBhuLbB2JNp97/GNVVlmGz4+iF/3IZsdfz5Aofz3Ow+DllG8wfduT8s1xZh1GjSsVJT9IDAH8SwFXmFE33v0uAvTRqKkcZIwhztVpal91RPuKVFdbMV31f42A15MldaVXqeAnET+AeZGzKH5osQ5ZE0MXJU=}, {secure: tkR4dcaMyrbUYV31q93bwfNcumxrhWZNNJ0VofaXiV2p4PAVM1HqY3uIzGQF1i1OMyrkhdeZ6JJUV/uXR6MCHtXywhyguBE0j9t8du4o8wS/fTsUHtXCz5yY+Z/5RcMPbvhhE0vXhpa66CkIIKAAZrfsNT7cs9OkA4w/PpYMZUVUhCCqAZTLcWc7w2fYmkoj/whUubruKDLnIx9lMma+lgh0vQO9gk6UvKMi5IjsQpKpY6Z/bTfuIzuaPpJNcMg/XlXeUpVezeTMPBE++quzSUrHfhVYD4OCk64KuEtwHjr2+jMeCS27fku/D+uBY1AfP5G7xewBu+fRGBZfd5gUVc7Iic2yD9e3VPOn+lQJx49bBz+zB2Y7DU7b+AtZC2gOoyRSQIpZa63tBf03MKJSqzBuPJo8LMOP4TJ1zFWPoHv7ErQoVZvhGfHO2/liB7eQDb6z5nb72tgZLTPvROvv/NTCs4mW+5BKSwGDarqJhuOO66n7Q1PlizAGhGg+Ldki1eGY8OsgIbwFJjtQgWZIpD5oWeBbduGS8F6ind3mMP9xheHzRW08ncJ2+4g6YEazLjKAt+IulhmNIPDrE720v6Htp664/tLqozKNrbvcKKXjXux5rRd+7S90AeogcF2+IjnH9ACDc99o3V3zAu/u/bRUk2RgVJXhqfBWpFBVUPo=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
